SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN (
    SELECT I_START.ITEM_ID
    FROM ITEM_INFO I_START, ITEM_TREE T, ITEM_INFO I_END
    WHERE T.PARENT_ITEM_ID = I_START.ITEM_ID
    AND I_END.ITEM_ID = T.ITEM_ID)
ORDER BY ITEM_ID DESC