WITH PROTECTED_PERIOD AS (
    SELECT I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME) + 1 AS PERIOD
    FROM ANIMAL_INS  I
    LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NOT NULL
    ORDER BY PERIOD DESC
)

SELECT ANIMAL_ID, NAME
FROM PROTECTED_PERIOD
LIMIT 2
