WITH MaxFavorites AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MaxFav
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
JOIN MaxFavorites mf ON r.FOOD_TYPE = mf.FOOD_TYPE AND r.FAVORITES = mf.MaxFav
ORDER BY r.FOOD_TYPE DESC;
