WITH YEAR_SALES AS (
    SELECT YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    U.GENDER,
    O.USER_ID
    FROM USER_INFO U, ONLINE_SALE O
    WHERE U.USER_ID = O.USER_ID
)

SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM YEAR_SALES
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER