WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR 
    UNION ALL
    SELECT HOUR+1 FROM TIME
    WHERE HOUR < 23
)

SELECT T.HOUR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT JOIN TIME T ON EXTRACT(HOUR FROM A.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY HOUR