WITH NEEDED_INFO AS (
    SELECT E.EMP_NO, E.EMP_NAME, E.SAL, G.SCORE
    FROM HR_EMPLOYEES E
    INNER JOIN (
        SELECT EMP_NO, AVG(SCORE) AS SCORE 
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) G ON E.EMP_NO = G.EMP_NO
), GRADE_INFO AS (
    SELECT EMP_NO,
    CASE
        WHEN SCORE >= 96 THEN 'S'
        WHEN SCORE >= 90 THEN 'A'
        WHEN SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SCORE >= 96 THEN 0.2
        WHEN SCORE >= 90 THEN 0.15
        WHEN SCORE >= 80 THEN 0.1
        ELSE 0
    END AS BONUS_RATIO
    FROM NEEDED_INFO
)

SELECT N.EMP_NO, N.EMP_NAME, G.GRADE, (N.SAL * G.BONUS_RATIO) AS BONUS
FROM NEEDED_INFO N
JOIN GRADE_INFO G ON N.EMP_NO = G.EMP_NO
ORDER BY N.EMP_NO
