SELECT I1_END.ITEM_ID, I1_END.ITEM_NAME, I1_END.RARITY
FROM ITEM_INFO I1_START, ITEM_TREE I2, ITEM_INFO I1_END
WHERE I1_START.RARITY = 'RARE'
AND I2.PARENT_ITEM_ID = I1_START.ITEM_ID
AND I1_END.ITEM_ID = I2.ITEM_ID
ORDER BY ITEM_ID DESC

