WITH SCORE_INFO AS (
    SELECT H1.EMP_NO,
    H1.EMP_NAME, H1.POSITION, H1.EMAIL, SUM(H2.SCORE) AS SCORE
    FROM HR_EMPLOYEES H1
    JOIN HR_GRADE H2 ON H1.EMP_NO = H2.EMP_NO
    GROUP BY H1.EMP_NO
)

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL 
FROM SCORE_INFO
ORDER BY SCORE DESC
LIMIT 1
