WITH ICECREAM_TABLE AS (
    SELECT F.SHIPMENT_ID, F.FLAVOR, F.TOTAL_ORDER, I.INGREDIENT_TYPE
    FROM FIRST_HALF F
    JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
)

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_TABLE
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER 