WITH RankFood AS (
    SELECT CATEGORY, PRICE, PRODUCT_NAME,
    ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT    
)

SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM RankFood RF
WHERE CATEGORY IN ('과자','국','김치','식용유')
AND RF.RNK = 1
ORDER BY PRICE DESC