WITH FishAverage AS (
    SELECT FISH_TYPE 
    FROM (
        SELECT FISH_TYPE, AVG(COALESCE(LENGTH, 10)) AS AVG_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) AS SUBQUERY
    WHERE AVG_LENGTH >= 33
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM FishAverage)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE